"""Add is_ai column to participant_table

Revision ID: 67e52809ad7b
Revises: 
Create Date: 2025-04-14 14:19:17.282333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e52809ad7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_table', schema=None) as batch_op:
        batch_op.drop_column('is_ai')

    # ### end Alembic commands ###
